# Copyright (C) 2026 YIQISOFT
# SPDX-License-Identifier: Apache-2.0

"""
`go-mod-core-contracts/v4/models`.

The three caches (`DeviceCache`, `DeviceProfileCache`, `ProvisionWatcherCache`) store
lightweight copies of the Core Metadata models. Those models are reproduced here as plain
dataclasses with fields aligned to `go-mod-core-contracts/v4/models` (which the Go SDK
imports). Every model provides a `clone()` method returning a deep copy, since the caches
hand out clones of the stored objects to avoid concurrent map access (mirroring the Go
`models.Device.Clone()` / `models.DeviceProfile.Clone()` / `models.ProvisionWatcher.Clone()`).

This module also defines the `CacheError` exception hierarchy used by all three caches as the
EdgeX` return values (`KindDuplicateName`,
`KindEntityDoesNotExist`, `KindContractInvalid`).
"""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

#: Protocol properties, i.e. a key/value map of a single protocol of a Device or
#: ProvisionWatcher. Aligned to `models.ProtocolProperties` (a `map[string]string`).
ProtocolProperties = Dict[str, str]


class CacheErrorKind(Enum):
    """Categorical identifier for cache errors.

    Kind` values used by the Go cache package.
    """
    DUPLICATE_NAME = "DuplicateName"
    ENTITY_DOES_NOT_EXIST = "NotFound"
    CONTRACT_INVALID = "ContractInvalid"


class CacheError(Exception):
    """Raised when a cache operation fails.

    EdgeX` error returned by the Go cache methods.
    Carries a `CacheErrorKind` so callers can distinguish duplicate names, missing
    entities and invalid contract values.
    """

    def __init__(self, kind: CacheErrorKind, message: str):
        super().__init__(message)
        self.kind = kind
        self.message = message


def create_cache_error(kind: CacheErrorKind, message: str) -> CacheError:
    """Create a `CacheError` with the given kind and message.

    """
    return CacheError(kind=kind, message=message)


class AdminState(str):
    """The admin state of a Device or ProvisionWatcher.

    Aligned to `models.AdminState` (a string type) with its two constants.
    """

    LOCKED = "LOCKED"
    UNLOCKED = "UNLOCKED"


#: Convenience constants mirroring `models.Locked` / `models.Unlocked`.
ADMIN_STATE_LOCKED = AdminState.LOCKED
ADMIN_STATE_UNLOCKED = AdminState.UNLOCKED


@dataclass
class AutoEvent:
    """A periodic, scheduled event generated by a Device.

    Aligned to `models.AutoEvent` in auto_event.go.

    Attributes:
        source_name: The name of the source that generates the event.
        on_change: Whether the event is generated only when the value changes.
        on_change_threshold: The threshold (for numeric values) that must be exceeded for
            the value to be considered changed when `on_change` is set.
        interval: The interval at which the event is generated (Go duration format, e.g.
            ``"30s"`` or ``"300ms"``).
    """
    source_name: str = ""
    on_change: bool = False
    on_change_threshold: float = 0.0
    interval: str = ""

    def clone(self) -> "AutoEvent":
        """Return a deep copy of this AutoEvent."""
        return copy.deepcopy(self)


@dataclass
class ResourceProperties:
    """The properties of a Device Resource.

Aligned to `models.ResourceProperties` in deviceresource.go. The optional numeric
    transformation fields use `None` to represent a missing (Go nil pointer) value.

    Attributes:
        value_type: The data type of the resource (see the `VALUETYPE_*` constants).
        read_write: The read/write permission of the resource ("R", "W" or "RW").
        units: The units of the resource value.
        minimum: The minimum value allowed for write operations (optional).
        maximum: The maximum value allowed for write operations (optional).
        default_value: The default value of the resource.
        mask: The mask applied when transforming the value (optional).
        shift: The bit shift applied when transforming the value (optional).
        scale: The scale factor applied when transforming the value (optional).
        offset: The offset applied when transforming the value (optional).
        base: The base applied when transforming the value (optional).
        assertion: A string the value is asserted against on read.
        media_type: The media type of the resource (for binary readings).
    """
    value_type: str = ""
    read_write: str = ""
    units: str = ""
    minimum: Optional[float] = None
    maximum: Optional[float] = None
    default_value: str = ""
    mask: Optional[int] = None
    shift: Optional[int] = None
    scale: Optional[float] = None
    offset: Optional[float] = None
    base: Optional[float] = None
    assertion: str = ""
    media_type: str = ""

    def clone(self) -> "ResourceProperties":
        """Return a deep copy of these ResourceProperties."""
        return copy.deepcopy(self)


@dataclass
class DeviceResource:
    """A data point on a Device that can be read or written to.

    Aligned to `models.DeviceResource` in deviceresource.go.

    Attributes:
        name: The name of the Device Resource.
        description: An optional description of the Device Resource.
        is_hidden: Whether the Device Resource is hidden from discovery.
        tag: An optional tag applied to the Device Resource.
        properties: The properties of the Device Resource.
        attributes: A key/value map of attributes for the Device Resource.
    """
    name: str = ""
    description: str = ""
    is_hidden: bool = False
    tag: str = ""
    properties: ResourceProperties = field(default_factory=ResourceProperties)
    attributes: Dict[str, Any] = field(default_factory=dict)

    def clone(self) -> "DeviceResource":
        """Return a deep copy of this DeviceResource."""
        return copy.deepcopy(self)


@dataclass
class ResourceOperation:
    """An operation that can be performed on a Device Resource.

    Aligned to `models.ResourceOperation` in resourceoperation.go.

    Attributes:
        device_resource: The name of the Device Resource the operation applies to.
        default_value: The default value used when the operation provides no value.
        mappings: A key/value map used to map the value to another string.
        attributes: A key/value map of attributes for the operation.
    """
    device_resource: str = ""
    default_value: str = ""
    mappings: Dict[str, str] = field(default_factory=dict)
    attributes: Dict[str, Any] = field(default_factory=dict)

    def clone(self) -> "ResourceOperation":
        """Return a deep copy of this ResourceOperation."""
        return copy.deepcopy(self)


@dataclass
class DeviceCommand:
    """A command that can be executed on a Device.

    Aligned to `models.DeviceCommand` in devicecommand.go.

    Attributes:
        name: The name of the Device Command.
        is_hidden: Whether the Device Command is hidden from discovery.
        read_write: The read/write permission of the command ("R", "W" or "RW").
        resource_operations: The ResourceOperations that make up the command.
    """
    name: str = ""
    is_hidden: bool = False
    read_write: str = ""
    resource_operations: List[ResourceOperation] = field(default_factory=list)

    def clone(self) -> "DeviceCommand":
        """Return a deep copy of this DeviceCommand."""
        return copy.deepcopy(self)


@dataclass
class Device:
    """A Device managed by the Device Service.

Aligned to `models.Device` in device.go. The caches store these objects and hand out
    clones on read.

    Attributes:
        id: The ID of the Device (a UUID generated for each new Device).
        name: The name of the Device.
        description: An optional description of the Device.
        admin_state: The admin state of the Device ("LOCKED" or "UNLOCKED").
        operating_state: The operating state of the Device ("UP" or "DOWN").
        service_name: The name of the Device Service that manages the Device.
        profile_name: The name of the Device Profile associated with the Device.
        labels: Labels applied to the Device.
        location: The Device's location.
        auto_events: The AutoEvents for the Device.
        protocols: The protocols the Device uses to communicate.
        last_connected: The time the Device last connected (nanoseconds).
        last_reported: The time the Device last reported (nanoseconds).
        tags: User-defined tags for the Device.
        properties: User-defined properties for the Device.
        created: The Unix timestamp when the Device was created.
        modified: The Unix timestamp when the Device was last modified.
    """
    id: str = ""
    name: str = ""
    description: str = ""
    admin_state: AdminState = ADMIN_STATE_UNLOCKED
    operating_state: str = ""
    service_name: str = ""
    profile_name: str = ""
    labels: List[str] = field(default_factory=list)
    location: Any = None
    auto_events: List[AutoEvent] = field(default_factory=list)
    protocols: Dict[str, ProtocolProperties] = field(default_factory=dict)
    last_connected: int = 0
    last_reported: int = 0
    tags: Dict[str, Any] = field(default_factory=dict)
    properties: Dict[str, Any] = field(default_factory=dict)
    created: int = 0
    modified: int = 0

    def clone(self) -> "Device":
        """Return a deep copy of this Device (mirrors `models.Device.Clone()`)."""
        return copy.deepcopy(self)


@dataclass
class DeviceProfile:
    """A collection of specifications that define a Device's capabilities.

Aligned to `models.DeviceProfile` in deviceprofile.go. The caches store these objects
    and hand out clones on read.

    Attributes:
        id: The ID of the Device Profile.
        name: The name of the Device Profile.
        description: An optional description of the Device Profile.
        manufacturer: The manufacturer of the Device Profile.
        model: The model of the Device Profile.
        labels: Labels applied to the Device Profile.
        device_resources: The DeviceResources defined by the Device Profile.
        device_commands: The DeviceCommands defined by the Device Profile.
        add_tags: Tags added to every Event generated for Devices using this Profile.
        properties: User-defined properties for the Device Profile.
        created: The Unix timestamp when the Device Profile was created.
        modified: The Unix timestamp when the Device Profile was last modified.
    """
    id: str = ""
    name: str = ""
    description: str = ""
    manufacturer: str = ""
    model: str = ""
    labels: List[str] = field(default_factory=list)
    device_resources: List[DeviceResource] = field(default_factory=list)
    device_commands: List[DeviceCommand] = field(default_factory=list)
    add_tags: Dict[str, Any] = field(default_factory=dict)
    properties: Dict[str, Any] = field(default_factory=dict)
    created: int = 0
    modified: int = 0

    def clone(self) -> "DeviceProfile":
        """Return a deep copy of this DeviceProfile (mirrors `models.DeviceProfile.Clone()`)."""
        return copy.deepcopy(self)


@dataclass
class ProvisionWatcherDiscoveredDevice:
    """Configuration for devices created from this ProvisionWatcher.

    Mirrors the ``DiscoveredDevice`` child object in the EdgeX ProvisionWatcher contract.
    Specifies the profile, admin state, auto events, and properties applied to
    devices created when a discovered device matches this watcher.
    """
    profile_name: str = ""
    admin_state: str = "UNLOCKED"
    labels: List[str] = field(default_factory=list)
    auto_events: List[AutoEvent] = field(default_factory=list)
    properties: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ProvisionWatcher:
    """A ProvisionWatcher used to automatically provision discovered Devices.

Aligned to `models.ProvisionWatcher` in provisionwatcher.go. The caches store these
    objects and hand out clones on read.

    Attributes:
        id: The ID of the ProvisionWatcher.
        name: The name of the ProvisionWatcher.
        description: An optional description of the ProvisionWatcher.
        service_name: The name of the Device Service the ProvisionWatcher is associated with.
        labels: Labels applied to the ProvisionWatcher.
        identifiers: The identifiers used to match discovered Devices.
        blocking_identifiers: The identifiers that prevent a discovered Device from matching.
        admin_state: The admin state of the ProvisionWatcher ("LOCKED" or "UNLOCKED").
        profile_name: The name of the Device Profile to apply to matched Devices.
        created: The Unix timestamp when the ProvisionWatcher was created.
        modified: The Unix timestamp when the ProvisionWatcher was last modified.
    """
    id: str = ""
    name: str = ""
    description: str = ""
    service_name: str = ""
    labels: List[str] = field(default_factory=list)
    identifiers: Dict[str, str] = field(default_factory=dict)
    blocking_identifiers: Dict[str, List[str]] = field(default_factory=dict)
    admin_state: AdminState = ADMIN_STATE_UNLOCKED
    profile_name: str = ""
    discovered_device: ProvisionWatcherDiscoveredDevice = field(default_factory=ProvisionWatcherDiscoveredDevice)
    created: int = 0
    modified: int = 0

    def clone(self) -> "ProvisionWatcher":
        """Return a deep copy of this ProvisionWatcher
        (mirrors `models.ProvisionWatcher.Clone()`)."""
        return copy.deepcopy(self)
